### ISSUE TITLE
Can't add TMItransient due to unsatisfiable requirements with TMI 

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/TMItransient.jl#28]
I can't add TMItransient to a project, may have started after changes made in #27 . Here is a MWE of activiating a new environment, and attempting to add TMItransient via GitHub 
```
(@v1.10) pkg> activate .
  Activating new project at `~`

(brynn) pkg> add https://github.com/ggebbie/TMItransient.jl.git
    Updating git-repo `https://github.com/ggebbie/TMItransient.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TMI [582500f6]:
 TMI [582500f6] log:
 ├─TMI [582500f6] has no known versions!
 └─restricted to versions * by TMItransient [ab8155c7] — no versions left
   └─TMItransient [ab8155c7] log:
     ├─possible versions are: 0.1.8 or uninstalled
```
I'm a little confused on the issue here - it seems like TMItransient wants TMI to be any version, but TMI doesn't have a version. Not sure what's up here!

**Comment by b-r-hamilton** [comment]
This may also be related to #26 . Trying to remove pin on ODE and updating now.

**Comment by ggebbie** [comment]
I found some insight by making a minimum working example:
```julia
] generate .
add https://github.com/ggebbie/TMI.jl
add https://github.com/ggebbie/TMItransient.jl
```

This environment pre-compiles fine and does not reproduce the error, pointing to some other problem in the cross-dependencies.

**Comment by ggebbie** [comment]
TMItransient had a few unneeded dependencies. Branch `minimal-env` removes these dependencies and passes tests. Perhaps one of these "extra" packages was causing a dependency conflict. Test by adding this branch to an environment rather than the main branch.

**Comment by b-r-hamilton** [comment]
I think this still doesn't work, unless I'm doing this wrong. I can try cloning that branch locally and adding the local branch to my project
```
(T1Lags) pkg> add https://github.com/ggebbie/TMItransient.jl#minimal-env
    Updating git-repo `https://github.com/ggebbie/TMItransient.jl`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TMI [582500f6]:
 TMI [582500f6] log:
 ├─TMI [582500f6] has no known versions!
 └─restricted to versions * by TMItransient [ab8155c7] — no versions left
   └─TMItransient [ab8155c7] log:
     ├─possible versions are: 0.1.8 or uninstalled
     └─TMItransient [ab8155c7] is fixed to version 0.1.8
```

**Comment by b-r-hamilton** [comment]
Tried cloning TMItransient#minimial-env, and then adding local package, same error 
```
(T1Lags) pkg> add /home/brynn/Code/TMItransient.jl/
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TMI [582500f6]:
 TMI [582500f6] log:
 ├─TMI [582500f6] has no known versions!
 └─restricted to versions * by TMItransient [ab8155c7] — no versions left
   └─TMItransient [ab8155c7] log:
     ├─possible versions are: 0.1.8 or uninstalled
     └─TMItransient [ab8155c7] is fixed to version 0.1.8
```

**Comment by ggebbie** [comment]
The first method of adding was correct.

Do you reproduce my MWE?

Can you provide the project environment that fails?

**Comment by b-r-hamilton** [comment]
1. Yes, if I start up a clean environment, and add TMI, and then add TMItransient it works. 
2. If I start up a clean environment, and then just add TMItransient, I get this error. 
So I think the error is related to adding TMItransient into a package that does not already have TMI installed.

**Comment by ggebbie** [comment]
very helpful clue - I reproduce your result in 2 above.d

**Comment by ggebbie** [comment]
Here's my understanding of the issue. Because TMI is not registered in the Julia general registry, you must add it before you add TMItransient.

https://discourse.julialang.org/t/package-manager-resolve-complaining-of-unsatisfiable-requirements-due-to-no-known-versions/23778

**Comment by b-r-hamilton** [comment]
I'm happy with that - glad to have this thread though for when I inevitably forget about this and reproduce this in the future. Thanks Jake!
